export const ENDPOINTS = Object.freeze({
  ping: "/wake",
  login: "/user/login",
  register: "/user/register",
  userInfo: "/user/details",
  updateUser: "/user/update",
  changePassword: "/user/update-login-key",
  logout: "/user/logout",
  budget: "/budget",
  expenses: "/expenses",
  summary: "/expenses/summary",
  list: "/expenses/list",
  search: "/expenses/search",
  plans: "/expense-plan",
  plansLite: "/expense-plan/list-lite",
  planDetails: "/expense-plan/details",
  copyExpenses: "/expense-plan/copy-to-budget",
  exportRange: "/export/range",
  exportPlan: "/export/plan",
  changelog: "/sys-info/changelog",
  contributor: "/sys-info/contributor",
  categories: "/categories/get-all",
  categoryGroups: "/categories/get-groups",
  yearStats: "/statistics/year-stats",
  recurringExpenses: "/recurring-expenses",
  processRecurringExpenses: "/recurring-expenses/process",
});
