export const ENDPOINTS = Object.freeze({
  ping: "/wake",
  login: "/user/login",
  register: "/user/register",
  userInfo: "/user/details",
  updateUser: "/user/update",
  changePassword: "/user/update-login-key",
  budget: "/budget",
  expenses: "/expenses",
  summary: "/expenses/summary",
  list: "/expenses/list",
  search: "/expenses/search",
  copyExpenses: "/expense-plan/copy-to-budget",
  categories: "/categories/get-all",
  plans: "/expense-plan",
  planDetails: "/expense-plan/details",
  downloadReport: "/reports",
  changelog: "/sys-info/changelog",
  contributor: "/sys-info/contributor",
  yearStats: "/statistics/year-stats",
});
