export const ENDPOINTS = Object.freeze({
  ping: "/wake",
  login: "/user/login",
  register: "/user/register",
  userInfo: "/user/details",
  updateUser: "/user/update",
  changePassword: "/user/change-password",
  budget: "/budget",
  expenses: "/expenses",
  summary: "/expenses/summary",
  list: "/expenses/list",
  search: "/expenses/search",
  plans: "/expense-plan",
  planDetails: "/expense-plan/details",
  copyExpenses: "/expense-plan/copy-to-budget",
  exportRange: "/export/range",
  exportPlan: "/export/plan",
  changelog: "/app-info/changelog",
  contributor: "/app-info/contributor",
  categories: "/categories/get-all",
  yearStats: "/statistics/year-stats",
});
